version: "3"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch_tinder
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9201:9201"
  web:
    build: .
    container_name: webapp_tinder
    ports:
      - "5000:5000"
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./:/tmp
    depends_on:
      - elastic
  notebook:
    container_name: notebook_tinder
    build: .
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/tmp